"""Added install date and attachment files

Revision ID: 5e5e498ecb5c
Revises: 632bff7bb8da
Create Date: 2026-06-28 09:11:17.859707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5e498ecb5c'
down_revision: Union[str, Sequence[str], None] = '632bff7bb8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return table in inspector.get_table_names() and any(
        item["name"] == column for item in inspector.get_columns(table)
    )


def _ensure_column(table: str, column: str, type_: sa.types.TypeEngine) -> None:
    if not _has_column(table, column):
        op.add_column(table, sa.Column(column, type_, nullable=True))


def _has_foreign_key(table: str, column: str, referred_table: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(
        column in (constraint.get("constrained_columns") or [])
        and constraint.get("referred_table") == referred_table
        for constraint in inspector.get_foreign_keys(table)
    )


def _ensure_foreign_key(table: str, column: str, referred_table: str, name: str) -> None:
    inspector = sa.inspect(op.get_bind())
    if (
        table in inspector.get_table_names()
        and referred_table in inspector.get_table_names()
        and not _has_foreign_key(table, column, referred_table)
    ):
        op.create_foreign_key(name, table, referred_table, [column], ["id"])


def _has_unique_constraint(table: str, column: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(
        set(constraint.get("column_names") or []) == {column}
        for constraint in inspector.get_unique_constraints(table)
    )


def upgrade() -> None:
    """Add install and attachment columns without failing on legacy schemas."""
    hardware_tables = ("component", "module", "subsystem", "system", "unit")
    for table in hardware_tables:
        _ensure_column(table, "installation_date", sa.DateTime())
        _ensure_column(table, "installed_by_id", sa.Integer())
        _ensure_column(table, "picture_url", sa.String())
        _ensure_column(table, "original_part_number", sa.String())
        _ensure_column(table, "original_serial_number", sa.String())
        _ensure_foreign_key(
            table, "installed_by_id", "user", f"fk_{table}_installed_by_id"
        )

    _ensure_column("configuration_history", "faulty_entity_id", sa.Integer())
    if (
        _has_column("configuration_history", "faulty_entity_id")
        and not _has_unique_constraint("configuration_history", "faulty_entity_id")
    ):
        op.create_unique_constraint(
            "uq_configuration_history_faulty_entity_id",
            "configuration_history",
            ["faulty_entity_id"],
        )
    _ensure_foreign_key(
        "configuration_history",
        "faulty_entity_id",
        "faulty_entity",
        "fk_configuration_history_faulty_entity_id",
    )

    if "inventory" in sa.inspect(op.get_bind()).get_table_names():
        _ensure_column("inventory", "holder_user_id", sa.Integer())
        if not _has_column("inventory", "added_date"):
            _ensure_column("inventory", "added_date", sa.DateTime())
        op.execute("UPDATE inventory SET added_date = NOW() WHERE added_date IS NULL")
        op.alter_column("inventory", "added_date", nullable=False)
        _ensure_column("inventory", "shelf_life_expires_at", sa.DateTime())
        _ensure_column("inventory", "picture_url", sa.String())
        _ensure_foreign_key(
            "inventory", "holder_user_id", "user", "fk_inventory_holder_user_id"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'original_serial_number')
    op.drop_column('unit', 'original_part_number')
    op.drop_column('unit', 'picture_url')
    op.drop_column('unit', 'installed_by_id')
    op.drop_column('unit', 'installation_date')
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.drop_column('system', 'original_serial_number')
    op.drop_column('system', 'original_part_number')
    op.drop_column('system', 'picture_url')
    op.drop_column('system', 'installed_by_id')
    op.drop_column('system', 'installation_date')
    op.drop_constraint(None, 'subsystem', type_='foreignkey')
    op.drop_column('subsystem', 'original_serial_number')
    op.drop_column('subsystem', 'original_part_number')
    op.drop_column('subsystem', 'picture_url')
    op.drop_column('subsystem', 'installed_by_id')
    op.drop_column('subsystem', 'installation_date')
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_column('module', 'original_serial_number')
    op.drop_column('module', 'original_part_number')
    op.drop_column('module', 'picture_url')
    op.drop_column('module', 'installed_by_id')
    op.drop_column('module', 'installation_date')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'picture_url')
    op.drop_column('inventory', 'shelf_life_expires_at')
    op.drop_column('inventory', 'added_date')
    op.drop_column('inventory', 'holder_user_id')
    op.drop_constraint(None, 'configuration_history', type_='foreignkey')
    op.drop_constraint(None, 'configuration_history', type_='unique')
    op.drop_column('configuration_history', 'faulty_entity_id')
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_column('component', 'original_serial_number')
    op.drop_column('component', 'original_part_number')
    op.drop_column('component', 'picture_url')
    op.drop_column('component', 'installed_by_id')
    op.drop_column('component', 'installation_date')
    # ### end Alembic commands ###
