"""Initial PLCM schema

Revision ID: 632bff7bb8da
Revises: 
Create Date: 2026-06-28 08:54:56.997304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '632bff7bb8da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('component', sa.Column('installed_by_id', sa.Integer(), nullable=True))
    op.add_column('component', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('component', sa.Column('original_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('component', sa.Column('original_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'component', 'user', ['installed_by_id'], ['id'])
    op.add_column('configuration_history', sa.Column('faulty_entity_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'configuration_history', ['faulty_entity_id'])
    op.create_foreign_key(None, 'configuration_history', 'faulty_entity', ['faulty_entity_id'], ['id'])
    op.add_column('inventory', sa.Column('holder_user_id', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('added_date', sa.DateTime(), nullable=False))
    op.add_column('inventory', sa.Column('shelf_life_expires_at', sa.DateTime(), nullable=True))
    op.add_column('inventory', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'user', ['holder_user_id'], ['id'])
    op.add_column('module', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('module', sa.Column('installed_by_id', sa.Integer(), nullable=True))
    op.add_column('module', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('module', sa.Column('original_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('module', sa.Column('original_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'module', 'user', ['installed_by_id'], ['id'])
    op.add_column('subsystem', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('subsystem', sa.Column('installed_by_id', sa.Integer(), nullable=True))
    op.add_column('subsystem', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subsystem', sa.Column('original_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subsystem', sa.Column('original_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'subsystem', 'user', ['installed_by_id'], ['id'])
    op.add_column('system', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('system', sa.Column('installed_by_id', sa.Integer(), nullable=True))
    op.add_column('system', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('system', sa.Column('original_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('system', sa.Column('original_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'system', 'user', ['installed_by_id'], ['id'])
    op.add_column('unit', sa.Column('installation_date', sa.DateTime(), nullable=True))
    op.add_column('unit', sa.Column('installed_by_id', sa.Integer(), nullable=True))
    op.add_column('unit', sa.Column('picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('unit', sa.Column('original_part_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('unit', sa.Column('original_serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'unit', 'user', ['installed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'original_serial_number')
    op.drop_column('unit', 'original_part_number')
    op.drop_column('unit', 'picture_url')
    op.drop_column('unit', 'installed_by_id')
    op.drop_column('unit', 'installation_date')
    op.drop_constraint(None, 'system', type_='foreignkey')
    op.drop_column('system', 'original_serial_number')
    op.drop_column('system', 'original_part_number')
    op.drop_column('system', 'picture_url')
    op.drop_column('system', 'installed_by_id')
    op.drop_column('system', 'installation_date')
    op.drop_constraint(None, 'subsystem', type_='foreignkey')
    op.drop_column('subsystem', 'original_serial_number')
    op.drop_column('subsystem', 'original_part_number')
    op.drop_column('subsystem', 'picture_url')
    op.drop_column('subsystem', 'installed_by_id')
    op.drop_column('subsystem', 'installation_date')
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_column('module', 'original_serial_number')
    op.drop_column('module', 'original_part_number')
    op.drop_column('module', 'picture_url')
    op.drop_column('module', 'installed_by_id')
    op.drop_column('module', 'installation_date')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'picture_url')
    op.drop_column('inventory', 'shelf_life_expires_at')
    op.drop_column('inventory', 'added_date')
    op.drop_column('inventory', 'holder_user_id')
    op.drop_constraint(None, 'configuration_history', type_='foreignkey')
    op.drop_constraint(None, 'configuration_history', type_='unique')
    op.drop_column('configuration_history', 'faulty_entity_id')
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_column('component', 'original_serial_number')
    op.drop_column('component', 'original_part_number')
    op.drop_column('component', 'picture_url')
    op.drop_column('component', 'installed_by_id')
    op.drop_column('component', 'installation_date')
    # ### end Alembic commands ###
